version: 2

models:
  - name: fct_rental
    description: "Model faktów łączący wypozyczenia z klientami, filmami etc."
    columns:
      - name: rental_id
        description: "Identyfikator wypozyczenia."
        
      - name: rental_date
        description: "Data wypozyczenia."
      
      - name: inventory_id
        description: "Identyfikator egzemplarza (kopii fizycznej) filmu."
      
      - name: film_id
        description: "Identyfikator filmu."
      
      - name: film_title
        description: "Tytul filmu."
      
      - name: customer_id
        description: "Identyfikator klienta."

      - name: customer_first_name
        description: "Imie klienta."
      
      - name: customer_last_name
        description: "Nazwisko klienta."
      
      - name: return_date
        description: "Data zwrotu."
      
      - name: staff_id
        description: "Identyfikator pracownika wypozyczalni."
      
      - name: staff_first_name
        description: "Imie pracownika."

      - name: staff_last_name
        description: "Nazwisko pracownika."

      